const listItemsCardhome = [
  // status:ing, done, fine, not
  {
    updated: ['21.04.15'],
    cardhome: [// 카드홈
      {
        listStart: false,
        sort: '카드홈',
        depth1: '비회원',
        depth2: '메인',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '서브',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '카드홈 서브(공통)',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '가입하기 안내',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '비로그인',
        depth2: '메인',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '서브',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '카드홈 서브(공통)',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '이용불가 안내',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'CH1000',
        url: '/cardhome/CH1000',
        startDate: '210430',
        endDate: '210430',
        finalDate: '',
        status: 'done fine',
        worker: '황지영',
        memos: ['회원/인증 > 이용불가 안내 와 같은 화면 사용']
      }, {
        listStart: false,
        sort: '',
        depth1: '로그인',
        depth2: '메인',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '서브',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '카드홈 서브(공통)',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210429',
        endDate: '210429',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['AS-IS 유지']
      }
    ]
  }
]

export default listItemsCardhome
