const listItemsJunior = [
  // status:ing, done, fine, not
  {
    updated: ['21.03.16'],
    junior: [// 주니어
      {
        listStart: false,
        sort: '',
        depth1: '주니어',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'JUNIOR000',
        url: '/junior/JUNIOR000',
        startDate: '210503',
        endDate: '210507',
        finalDate: '210927',
        status: 'done fine',
        worker: '김병화',
        memos: ['210618 스켈레톤UI 추가', '210715 결제 케이스 추가', '210916 새로고침 버튼 추가 및 수정', '210927 비로그인 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '안내',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR001',
        url: '/junior/JUNIOR001',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210824',
        status: 'done fine',
        worker: '우현주',
        memos: ['210824 18세->19세 텍스트 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '튜토리얼',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '마이신한포인트',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'LP',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '포인트 전환하기',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR002',
        url: '/junior/JUNIOR002',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ['210727 삭제']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '충전완료(Type1)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'JUNIOR004',
        url: '/junior/JUNIOR004',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210826',
        status: 'done fine',
        worker: '우현주',
        memos: ['210614 이미지 수정', '210709 .full-body2 클래스 수정', '210826 로티 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '충전완료(Type2)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'JUNIOR005',
        url: '/junior/JUNIOR005',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210826',
        status: 'done fine',
        worker: '우현주',
        memos: ['210614 이미지 수정', '210709 .full-body2 클래스 수정', '210826 로티 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '결제',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: '',
        url: '',
        startDate: '210430',
        endDate: '210430',
        finalDate: '',
        status: 'native',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '결제카드 선택',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR006',
        url: '/junior/JUNIOR006',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210706',
        status: 'done fine',
        worker: '우현주',
        memos: ['210706 타이틀 텍스트 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '송금',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'LP',
        page: '',
        url: '',
        startDate: '210430',
        endDate: '210430',
        finalDate: '',
        status: 'native',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '포인트 즉시적립',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'LP',
        page: '',
        url: '',
        startDate: '210430',
        endDate: '210430',
        finalDate: '',
        status: 'native',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '공유하기',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR007',
        url: '/junior/JUNIOR007',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '오늘의 퀴즈(OX)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR008',
        url: '/junior/JUNIOR008',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210602',
        status: 'done fine',
        worker: '우현주',
        memos: ['210602 상단 정렬 클래스 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '오늘의 퀴즈(객관식)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR009',
        url: '/junior/JUNIOR009',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210602',
        status: 'done fine',
        worker: '우현주',
        memos: ['210602 상단 정렬 클래스 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '오늘의 퀴즈(주관식)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'JUNIOR010',
        url: '/junior/JUNIOR010',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210524',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '이벤트',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'JUNIOR000',
        url: '/junior/JUNIOR000',
        startDate: '210503',
        endDate: '210507',
        finalDate: '',
        status: 'done fine',
        worker: '김병화',
        memos: ''
      }
    ]
  }
]

export default listItemsJunior
