const listItemsIntegrate = [
  // status:ing, done, fine, not
  {
    updated: ['21.03.16'],
    integrate: [// 가이드
      {
        listStart: false,
        sort: '통합가이드',
        depth1: '통합가이드',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'MAIN',
        url: '/integrate/MAIN',
        startDate: '210428',
        endDate: '210428',
        finalDate: '210906',
        status: 'done fine',
        worker: '우현주',
        memos: ['210830 .item-full 클래스 수정, 텍스트 수정', '210906 텍스트, 이미지 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '빠르게 둘러보기(TBD)',
        depth3: '페이판이 처음이라면',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210527',
        endDate: '210527',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '월렛',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210527',
        endDate: '210527',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '내자산',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210527',
        endDate: '210527',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '디스커버',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210527',
        endDate: '210527',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '가이드 따라해보기',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'GUIDE001',
        url: '/integrate/GUIDE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '210913',
        status: 'done fine',
        worker: '우현주',
        memos: ['210913 인풋 지우기 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '검색',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'GUIDE001',
        url: '/integrate/GUIDE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '검색어 입력',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'GUIDE001',
        url: '/integrate/GUIDE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '검색결과',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'GUIDE001',
        url: '/integrate/GUIDE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '검색결과 없음',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'GUIDE002',
        url: '/integrate/GUIDE002',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '전체보기',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'GUIDE001',
        url: '/integrate/GUIDE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '시작하기',
        depth4: '메뉴 순서 바꾸기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '월렛',
        depth4: '오픈뱅킹 이용하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '계좌로 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '현장에서 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '스캔・코드입력 결제',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '온라인에서 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '카드로 송금하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '신한Pay머니로 송금하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '계좌로 송금하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '신한Pay머니 충전하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '결제기능 더보기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '카드・계좌 관리하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '이용내역 한눈에 보기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '이용금액 숨기기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '엣지패널로 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '흔들어서 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: 'NFC로 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '자산',
        depth4: '마이데이터 연결하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '금융캘린더 활용하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '예산 설정하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '금융상품 추천받기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '정보계좌 활용하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '신용점수 관리하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '버킷리스트 설정하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '데이터 재테크하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '디스커버',
        depth4: '관심사 설정하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '관심 커뮤니티 설정하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '포인트 쌓기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '혜택 한눈에 보기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '타임라인',
        depth4: '영수증 정보 확인하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '이용내역 쉽게 찾기 ',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '이용내역 숨기기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '전체메뉴',
        depth4: '챗봇으로 문의하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '궁금한 내용 검색하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '신한pLay 살펴보기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '자동로그인 설정하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '인증서 사용하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '필요한 알림만 설정하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '홈스크린으로 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '단축어로 결제하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '위젯 이용하기',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: '',
        url: '',
        startDate: '210706',
        endDate: '210709',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ['홈페이지 연동 HTML']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '서비스 살펴보기',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'SERVICE001',
        url: '/integrate/SERVICE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '210709',
        status: 'done fine',
        worker: '우현주',
        memos: ['210709 서비스명 전체 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '검색',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210525',
        endDate: '210525',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '검색어 입력',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210525',
        endDate: '210525',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '검색결과',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210525',
        endDate: '210525',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '검색결과 없음',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210525',
        endDate: '210525',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '월렛',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'SERVICE001',
        url: '/integrate/SERVICE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '월렛 서비스안내',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '바코드결제 서비스안내',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '터치결제 서비스안내',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: 'NFC결제 서비스안내',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '신한Pay머니 서비스안내',
        depth5: '',
        depth6: '',
        type: 'P',
        page: '',
        url: '',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '내자산',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'SERVICE001',
        url: '/integrate/SERVICE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '디스커버',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'SERVICE001',
        url: '/integrate/SERVICE001',
        startDate: '210428',
        endDate: '210428',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }
    ]
  }
]

export default listItemsIntegrate
