const listItemsSenior = [
  // status:ing, done, fine, not
  {
    updated: ['21.03.16'],
    senior: [// 시니어
      {
        listStart: false,
        sort: '',
        depth1: '시니어',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'SENIOR002',
        url: '/senior/SENIOR002',
        startDate: '210426',
        endDate: '210426',
        finalDate: '210927',
        status: 'done fine',
        worker: '우현주',
        memos: ['210611 스켈레톤UI 추가', '210616 슬라이드 이미지 수정 및 추가', '210618 카드브랜드 경로 수정', '210621 카드회전 수정', '210715 결제 케이스 추가 및 더보기 수정', '210716 클래스 수정', '210927 비로그인 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '메인(카드없는경우)',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'SENIOR003',
        url: '/senior/SENIOR003',
        startDate: '210428',
        endDate: '210428',
        finalDate: '210616',
        status: 'done fine',
        worker: '우현주',
        memos: ['210616 슬라이드 이미지 수정 및 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '안내',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'SENIOR001',
        url: '/senior/SENIOR001',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ['210602 서비스 모드는 ~ 텍스트 삭제']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '통합검색',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '터치결제',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: 'QR결제',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '명세서',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '주간 리포트',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '배너',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '혜택',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'L',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '올댓쇼핑',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'L',
        page: '',
        url: '',
        startDate: '210426',
        endDate: '210426',
        finalDate: '',
        status: 'delete',
        worker: '우현주',
        memos: ''
      }
    ]
  }
]

export default listItemsSenior
