const listItemsEtc = [
  // status:ing, done, fine, not
  {
    updated: ['21.03.16'],
    etc: [// 기타
      {
        listStart: false,
        sort: 'FAN 관리',
        depth1: '전시 콘텐츠 생성/관리',
        depth2: '팝업관리',
        depth3: 'Popup Type A',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC100',
        url: '/etc/ETC100',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type B',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC200',
        url: '/etc/ETC200',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type C',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC300',
        url: '/etc/ETC300',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type C(한줄)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC400',
        url: '/etc/ETC400',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type D',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC500',
        url: '/etc/ETC500',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type D(한줄)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC600',
        url: '/etc/ETC600',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type D-2',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC601',
        url: '/etc/ETC601',
        startDate: '210812',
        endDate: '210813',
        finalDate: '',
        status: 'done fine',
        worker: '홍지영',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type D-3',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC602',
        url: '/etc/ETC602',
        startDate: '210812',
        endDate: '210812',
        finalDate: '',
        status: 'done fine',
        worker: '홍지영',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type G-1',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'ETC700',
        url: '/etc/ETC700',
        startDate: '210615',
        endDate: '210615',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['210812 class 추가 : type2']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type G-2',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'ETC800',
        url: '/etc/ETC800',
        startDate: '210615',
        endDate: '210617',
        finalDate: '210812',
        status: 'done fine',
        worker: '우현주',
        memos: ['아이폰에서 .ios-ver 추가', '210812 체크박스 추가, 닫기 버튼 수정']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type G-3',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'ETC801',
        url: '/etc/ETC801',
        startDate: '210812',
        endDate: '210812',
        finalDate: '',
        status: 'done fine',
        worker: '홍지영',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type G-3(한줄)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: 'ETC802',
        url: '/etc/ETC802',
        startDate: '210812',
        endDate: '210812',
        finalDate: '',
        status: 'done fine',
        worker: '홍지영',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup Type G',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: '',
        url: '',
        startDate: '000000',
        endDate: '000000',
        finalDate: '',
        status: 'delete',
        worker: '',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: 'Popup-긴급공지 템플릿',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'AP',
        page: 'ETC900',
        url: '/etc/ETC900',
        startDate: '210615',
        endDate: '210617',
        finalDate: '210813',
        status: 'done fine',
        worker: '우현주',
        memos: ['210813 타이틀 추가']
      }, {
        listStart: true,
        sort: '고객센터',
        depth1: '공지사항',
        depth2: '',
        depth3: '공지사항목록',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'PAYFM302R25',
        url: '/allmenu/PAYFM302R25',
        startDate: '210610',
        endDate: '210610',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '',
        depth4: '공지사항 상세',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'PAYFM302R26',
        url: '/allmenu/PAYFM302R26',
        startDate: '210610',
        endDate: '210610',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: true,
        sort: '공통',
        depth1: '바텀 메뉴',
        depth2: '',
        depth3: '주니어',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: '',
        url: '',
        startDate: '210614',
        endDate: '210614',
        finalDate: '',
        status: 'native',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '일반',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: '',
        url: '',
        startDate: '210614',
        endDate: '210614',
        finalDate: '',
        status: 'native',
        worker: '김성준',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '시니어',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'BP',
        page: '',
        url: '',
        startDate: '210614',
        endDate: '210614',
        finalDate: '',
        status: 'native',
        worker: '김성준',
        memos: ''
      }, {
        listStart: true,
        sort: '이벤트',
        depth1: '이벤트 모듈',
        depth2: '보물찾기',
        depth3: '보물발견',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: 'ETC1000',
        url: '/etc/ETC1000',
        startDate: '210503',
        endDate: '210507',
        finalDate: '210609',
        status: 'done fine',
        worker: '김병화',
        memos: ['210609 인터렉션 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '보물확인',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: 'ETC1100',
        url: '/etc/ETC1100',
        startDate: '210503',
        endDate: '210507',
        finalDate: '210609',
        status: 'done fine',
        worker: '김병화',
        memos: ['210609 인터렉션 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '보물확인(버튼없음)',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: 'ETC1200',
        url: '/etc/ETC1200',
        startDate: '210503',
        endDate: '210507',
        finalDate: '210609',
        status: 'done fine',
        worker: '김병화',
        memos: ['210609 인터렉션 추가']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '',
        depth3: '보물확인 후',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'FP',
        page: 'ETC1300',
        url: '/etc/ETC1300',
        startDate: '210503',
        endDate: '210507',
        finalDate: '',
        status: 'delete',
        worker: '김병화',
        memos: ['스펙아웃']
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: 'OX퀴즈',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: '',
        url: '',
        startDate: '210525',
        endDate: '210525',
        finalDate: '',
        status: 'delete',
        worker: '김병화',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '이벤트 포인트 적립',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: '',
        url: '',
        startDate: '210525',
        endDate: '210525',
        finalDate: '',
        status: 'delete',
        worker: '김병화',
        memos: ''
      }, {
        listStart: true,
        sort: '공통',
        depth1: '로딩 영역',
        depth2: '스캘래톤 UI',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'PAYFM500R01',
        url: '/timeline/PAYFM500R01',
        startDate: '210608',
        endDate: '210608',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '공통 화면전환 로딩 애니메이션 화면',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'ETC2000',
        url: '/etc/ETC2000',
        startDate: '210610',
        endDate: '210610',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '동일화면 내공통 로딩 애니메이션',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'ETC2100',
        url: '/etc/ETC2100',
        startDate: '210610',
        endDate: '210610',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '공통 스피너',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'S',
        page: 'guide_loader',
        url: '/basic-libs/libsLoader',
        startDate: '210610',
        endDate: '210610',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '헤더 프로그레스 바',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: '',
        url: '',
        startDate: '210614',
        endDate: '210614',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['개발 처리']
      }, {
        listStart: false,
        sort: '',
        depth1: '에러페이지',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'ETC3000',
        url: '/etc/ETC3000',
        startDate: '210617',
        endDate: '210617',
        finalDate: '',
        status: 'done fine',
        worker: '우현주',
        memos: ''
      }, {
        listStart: false,
        sort: '',
        depth1: '신한플러스 플로팅 버튼',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: 'P',
        page: 'WL8210',
        url: '/wallet/WL8210',
        startDate: '210617',
        endDate: '210617',
        finalDate: '',
        status: 'done fine',
        worker: '김성준',
        memos: ''
      }, {
        listStart: true,
        sort: '비쥬얼',
        depth1: '디스커버 올댓 디폴트 이미지 160개 Type',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: '',
        url: '',
        startDate: '210614',
        endDate: '210614',
        finalDate: '',
        status: 'delete',
        worker: '김성준',
        memos: ['개발 전달']
      }
    ]
  }
]

export default listItemsEtc
