const listItemsPrevious = [
  // status:ing, done, fine, not
  {
    updated: ['21.03.16'],
    previous: [// 선행 개발
      {
        listStart: false,
        sort: '랜딩페이지',
        depth1: '랜딩페이지',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'landing',
        url: '/shpayfan/landing',
        startDate: '210208',
        endDate: '210215',
        finalDate: '',
        status: 'done',
        worker: '홍지영',
        memos: ['210223 홍지영 header 이전, 홈 버튼 추가']
      },
      {
        listStart: false,
        sort: '로그인',
        depth1: '로그인',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'login',
        url: '/shpayfan/login/login',
        startDate: '210208',
        endDate: '210215',
        finalDate: '',
        status: 'done',
        worker: '홍지영',
        memos: ['210223 홍지영 header 이전, 홈 버튼 추가']
      },
      {
        listStart: false,
        sort: '타임라인',
        depth1: '타임라인-목록 리스트',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'TL001',
        url: '/shpayfan/timeline/TL001',
        startDate: '210208',
        endDate: '210215',
        finalDate: '',
        status: 'done',
        worker: '김성준',
        memos: ['210223 홍지영 header 이전, 홈 버튼 추가']
      },
      {
        listStart: false,
        sort: '',
        depth1: '타임라인-상세 페이지',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'TL002',
        url: '/shpayfan/timeline/TL002',
        startDate: '210208',
        endDate: '210215',
        finalDate: '',
        status: 'done',
        worker: '우현주',
        memos: ''
      },
      {
        listStart: false,
        sort: '',
        depth1: '커뮤니티-목록 리스트',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'BD001',
        url: '/shpayfan/board/BD001',
        startDate: '210208',
        endDate: '210215',
        finalDate: '',
        status: 'done',
        worker: '홍지영',
        memos: ['210223 홍지영 header 이전 홈 버튼 추가', '210223 홍지영 페이징 버튼 추가']
      },
      {
        listStart: false,
        sort: '',
        depth1: '커뮤니티-수정/삭제',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'BD002',
        url: '/shpayfan/board/BD002',
        startDate: '210208',
        endDate: '210215',
        finalDate: '',
        status: 'done',
        worker: '홍지영',
        memos: ['210223 홍지영 header 이전, 홈 버튼 추가']
      },
      {
        listStart: false,
        sort: '',
        depth1: '커뮤니티-등록/취소',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'BD003',
        url: '/shpayfan/board/BD003',
        startDate: '210208',
        endDate: '000000',
        finalDate: '',
        status: 'done',
        worker: '홍지영',
        memos: ['210223 홍지영 header 이전, 홈 버튼 추가', '210223 홍지영 인풋 타이틀 추가']
      },
      {
        listStart: false,
        sort: '자산',
        depth1: '카드목록조회',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'AT001',
        url: '/shpayfan/mydata/AT001',
        startDate: '210223',
        endDate: '210223',
        finalDate: '',
        status: 'done',
        worker: '김상아',
        memos: ''
      },
      {
        listStart: false,
        sort: '',
        depth1: '',
        depth2: '카드이용내역',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'AT0012',
        url: '/shpayfan/mydata/AT0012',
        startDate: '210223',
        endDate: '210223',
        finalDate: '',
        status: 'done',
        worker: '김상아',
        memos: ''
      },
      {
        listStart: false,
        sort: '',
        depth1: '추천조회',
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        type: '',
        page: 'AT001',
        url: '/shpayfan/mydata/AT001',
        startDate: '210223',
        endDate: '210223',
        finalDate: '',
        status: 'done',
        worker: '김상아',
        memos: ''
      }
    ]
  }
]

export default listItemsPrevious
